var sixieme1=[
    {
        "nom": "ABORO DOMINIQUE",
        "dictee": "7",
        "exp": "10,66",
        "pc": "6,33",
        "anglais": "7,67",
        "hg": "8,08",
        "svt": "9,83",
        "maths": "13,16",
        "info": "10",
        "eps": "11,67",
        "art": "6,75",
        "moyenne": "9,11",
        "rang": "10",
        "trimestre": "1"
    },
    {
        "nom": "BOYO Lucia",
        "dictee": "14,66",
        "exp": "11,83",
        "pc": "13,66",
        "anglais": "16,17",
        "hg": "14,16",
        "svt": "14",
        "maths": "16,66",
        "info": "15,83",
        "eps": "13,85",
        "art": "12,5",
        "moyenne": "14,33",
        "rang": "2",
        "trimestre": "1"
    },
    {
        "nom": "HOUSSIKA Ranchenelle",
        "dictee": "9,5",
        "exp": "10,16",
        "pc": "8,33",
        "anglais": "4,5",
        "hg": "7,08",
        "svt": "8,88",
        "maths": "15,16",
        "info": "16",
        "eps": "13",
        "art": "6",
        "moyenne": "9,86",
        "rang": "9",
        "trimestre": "1"
    },
    {
        "nom": "MBOUSSY MATSOUELE",
        "dictee": "11,16",
        "exp": "12,83",
        "pc": "11",
        "anglais": "8,92",
        "hg": "10,08",
        "svt": "10,33",
        "maths": "15,83",
        "info": "11,33",
        "eps": "13",
        "art": "8,25",
        "moyenne": "11,07",
        "rang": "6",
        "trimestre": "1"
    },
    {
        "nom": "MOUYAKA MOUSSANGA",
        "dictee": "8,83",
        "exp": "12,83",
        "pc": "14",
        "anglais": "13,33",
        "hg": "12,91",
        "svt": "13,11",
        "maths": "17",
        "info": "16,33",
        "eps": "13,67",
        "art": "9,5",
        "moyenne": "13,15",
        "rang": "5",
        "trimestre": "1"
    },
    {
        "nom": "NGOMA TOULA Rose",
        "dictee": "11,5",
        "exp": "11,66",
        "pc": "14,33",
        "anglais": "12,54",
        "hg": "12,33",
        "svt": "13,77",
        "maths": "15,83",
        "info": "16,33",
        "eps": "12,33",
        "art": "11,5",
        "moyenne": "13,21",
        "rang": "4",
        "trimestre": "1"
    },
    {
        "nom": "NGOUAKA Joyce",
        "dictee": "9,66",
        "exp": "10,16",
        "pc": "8,33",
        "anglais": "11",
        "hg": "10,5",
        "svt": "9,77",
        "maths": "14,83",
        "info": "9,58",
        "eps": "15",
        "art": "7",
        "moyenne": "10,58",
        "rang": "7",
        "trimestre": "1"
    },
    {
        "nom": "NGUELEE IKOUBOU",
        "dictee": "15",
        "exp": "13",
        "pc": "16",
        "anglais": "14,29",
        "hg": "18,58",
        "svt": "16,66",
        "maths": "17",
        "info": "18,66",
        "eps": "14,33",
        "art": "12,87",
        "moyenne": "15,63",
        "rang": "1",
        "trimestre": "1"
    },
    {
        "nom": "NSIKOU Marie",
        "dictee": "14,33",
        "exp": "11",
        "pc": "7,33",
        "anglais": "12,25",
        "hg": "5,33",
        "svt": "7,88",
        "maths": "14,5",
        "info": "10,16",
        "eps": "15",
        "art": "6,5",
        "moyenne": "10,42",
        "rang": "8",
        "trimestre": "1"
    },
    {
        "nom": "OSSOUALA Marie",
        "dictee": "14,83",
        "exp": "13,83",
        "pc": "16,5",
        "anglais": "12,75",
        "hg": "14,91",
        "svt": "6,3",
        "maths": "14,33",
        "info": "15",
        "eps": "12",
        "art": "12,87",
        "moyenne": "13,33",
        "rang": "3",
        "trimestre": "1"
    },
    {
        "nom": "TATY Luc",
        "dictee": "4,5",
        "exp": "7,83",
        "pc": "6",
        "anglais": "3,33",
        "hg": "5,58",
        "svt": "7,22",
        "maths": "12,5",
        "info": "8,33",
        "eps": "14,33",
        "art": "7",
        "moyenne": "7,66",
        "rang": "11",
        "trimestre": "1"
    }
]
var sixieme2=[
    {
        "nom": "ABORO DOMINIQUE",
        "dictee": "9,66",
        "exp": "9,66",
        "pc": "7",
        "anglais": "10,63",
        "hg": "12,16",
        "svt": "10,44",
        "maths": "12,66",
        "info": "11,16",
        "eps": "14",
        "art": "5,29",
        "moyenne": "10,27",
        "rang": "8",
        "trimestre": "2"
    },
    {
        "nom": "BOYO Lucia",
        "dictee": "18,16",
        "exp": "12,33",
        "pc": "14,33",
        "anglais": "13,08",
        "hg": "17",
        "svt": "16,16",
        "maths": "16,66",
        "info": "16,33",
        "eps": "12",
        "art": "13,62",
        "moyenne": "14,97",
        "rang": "2",
        "trimestre": "2"
    },
    {
        "nom": "HOUSSIKA Ranchenelle",
        "dictee": "9,83",
        "exp": "11",
        "pc": "6,66",
        "anglais": "6",
        "hg": "9,25",
        "svt": "9,61",
        "maths": "14,83",
        "info": "11",
        "eps": "13,66",
        "art": "4,08",
        "moyenne": "9,59",
        "rang": "10",
        "trimestre": "2"
    },
    {
        "nom": "MBOUSSY MATSOUELE",
        "dictee": "13,66",
        "exp": "11,33",
        "pc": "9,33",
        "anglais": "10,25",
        "hg": "11,66",
        "svt": "11,72",
        "maths": "15",
        "info": "12,33",
        "eps": "14",
        "art": "6,66",
        "moyenne": "11,59",
        "rang": "7",
        "trimestre": "2"
    },
    {
        "nom": "MOUYAKA MOUSSANGA",
        "dictee": "12,33",
        "exp": "10,16",
        "pc": "12,66",
        "anglais": "10,96",
        "hg": "11,91",
        "svt": "11",
        "maths": "16,16",
        "info": "14,83",
        "eps": "15,16",
        "art": "9,29",
        "moyenne": "12,45",
        "rang": "5",
        "trimestre": "2"
    },
    {
        "nom": "NGOMA TOULA Rose",
        "dictee": "15,5",
        "exp": "12",
        "pc": "10,66",
        "anglais": "13,75",
        "hg": "14,5",
        "svt": "12,27",
        "maths": "16,83",
        "info": "15,33",
        "eps": "12,83",
        "art": "6,91",
        "moyenne": "13,06",
        "rang": "3",
        "trimestre": "2"
    },
    {
        "nom": "NGOUAKA Joyce",
        "dictee": "8,16",
        "exp": "10",
        "pc": "5",
        "anglais": "10,08",
        "hg": "10,5",
        "svt": "6,33",
        "maths": "14,83",
        "info": "12,33",
        "eps": "14,83",
        "art": "6,5",
        "moyenne": "9,86",
        "rang": "9",
        "trimestre": "2"
    },
    {
        "nom": "NGUELEE IKOUBOU",
        "dictee": "15,16",
        "exp": "12",
        "pc": "13,33",
        "anglais": "18,08",
        "hg": "18,83",
        "svt": "14,33",
        "maths": "17",
        "info": "14,83",
        "eps": "14",
        "art": "12,37",
        "moyenne": "14,99",
        "rang": "1",
        "trimestre": "2"
    },
    {
        "nom": "NSIKOU Marie",
        "dictee": "16,66",
        "exp": "11,33",
        "pc": "4",
        "anglais": "13,38",
        "hg": "9,66",
        "svt": "12,38",
        "maths": "15,16",
        "info": "12,66",
        "eps": "15,66",
        "art": "9,75",
        "moyenne": "12,06",
        "rang": "6",
        "trimestre": "2"
    },
    {
        "nom": "OSSOUALA Marie",
        "dictee": "17",
        "exp": "13",
        "pc": "12",
        "anglais": "10,54",
        "hg": "16,66",
        "svt": "7,05",
        "maths": "15,66",
        "info": "11,5",
        "eps": "13",
        "art": "13,66",
        "moyenne": "13,01",
        "rang": "4",
        "trimestre": "2"
    },
    {
        "nom": "TATY Luc",
        "dictee": "6,5",
        "exp": "10,83",
        "pc": "10,33",
        "anglais": "8,58",
        "hg": "9",
        "svt": "6,65",
        "maths": "12,83",
        "info": "8",
        "eps": "14,66",
        "art": "6,5",
        "moyenne": "9,39",
        "rang": "11",
        "trimestre": "2"
    }
];
var sixieme3=[
    {
        "nom": "ABORO DOMINIQUE",
        "dictee": "9,66",
        "exp": "10,66",
        "pc": "12",
        "anglais": "9,63",
        "hg": "10",
        "svt": "9,88",
        "maths": "14,33",
        "info": "8,87",
        "eps": "13",
        "art": "7,5",
        "moyenne": "10,55",
        "rang": "11",
        "trimestre": "3"
    },
    {
        "nom": "BOYO Lucia",
        "dictee": "19,66",
        "exp": "14",
        "pc": "13",
        "anglais": "16,55",
        "hg": "12",
        "svt": "14,16",
        "maths": "16,83",
        "info": "14,31",
        "eps": "13",
        "art": "15,08",
        "moyenne": "14,86",
        "rang": "2",
        "trimestre": "3"
    },
    {
        "nom": "HOUSSIKA Ranchenelle",
        "dictee": "13",
        "exp": "12",
        "pc": "11",
        "anglais": "10,25",
        "hg": "10",
        "svt": "10,16",
        "maths": "15,66",
        "info": "9,38",
        "eps": "14,08",
        "art": "9,58",
        "moyenne": "11,51",
        "rang": "10",
        "trimestre": "3"
    },
    {
        "nom": "MBOUSSY MATSOUELE",
        "dictee": "13,16",
        "exp": "11",
        "pc": "11,66",
        "anglais": "13,3",
        "hg": "10,66",
        "svt": "10,5",
        "maths": "15,5",
        "info": "11,16",
        "eps": "12,5",
        "art": "9,5",
        "moyenne": "11,89",
        "rang": "9",
        "trimestre": "3"
    },
    {
        "nom": "MOUYAKA MOUSSANGA",
        "dictee": "10,83",
        "exp": "10,83",
        "pc": "13,33",
        "anglais": "17,52",
        "hg": "18,83",
        "svt": "12,61",
        "maths": "16",
        "info": "15,48",
        "eps": "11,83",
        "art": "12,16",
        "moyenne": "13,94",
        "rang": "4",
        "trimestre": "3"
    },
    {
        "nom": "NGOMA TOULA Rose",
        "dictee": "17,66",
        "exp": "13",
        "pc": "12,33",
        "anglais": "12,63",
        "hg": "18",
        "svt": "13,16",
        "maths": "17,16",
        "info": "13,75",
        "eps": "12,33",
        "art": "11,25",
        "moyenne": "14,13",
        "rang": "3",
        "trimestre": "3"
    },
    {
        "nom": "NGOUAKA Joyce",
        "dictee": "9,5",
        "exp": "11,66",
        "pc": "11",
        "anglais": "15,05",
        "hg": "15,08",
        "svt": "10,72",
        "maths": "15,16",
        "info": "11,47",
        "eps": "13,33",
        "art": "10,33",
        "moyenne": "12,33",
        "rang": "8",
        "trimestre": "3"
    },
    {
        "nom": "NGUELEE IKOUBOU",
        "dictee": "14,83",
        "exp": "11,66",
        "pc": "18,33",
        "anglais": "14,58",
        "hg": "16,75",
        "svt": "16,94",
        "maths": "17,33",
        "info": "13,26",
        "eps": "14,16",
        "art": "13,16",
        "moyenne": "15,10",
        "rang": "1",
        "trimestre": "3"
    },
    {
        "nom": "NSIKOU Marie",
        "dictee": "17,33",
        "exp": "11,66",
        "pc": "10,66",
        "anglais": "13,75",
        "hg": "9,83",
        "svt": "9,16",
        "maths": "14,16",
        "info": "13,37",
        "eps": "14,66",
        "art": "11,83",
        "moyenne": "12,64",
        "rang": "7",
        "trimestre": "3"
    },
    {
        "nom": "OSSOUALA Marie",
        "dictee": "17",
        "exp": "12,66",
        "pc": "12,33",
        "anglais": "13,38",
        "hg": "13,83",
        "svt": "15,61",
        "maths": "16,5",
        "info": "13,87",
        "eps": "11,83",
        "art": "12,33",
        "moyenne": "13,93",
        "rang": "5",
        "trimestre": "3"
    },
    {
        "nom": "TATY Luc",
        "dictee": "9,5",
        "exp": "9,16",
        "pc": "4,33",
        "anglais": "6,61",
        "hg": "6,83",
        "svt": "7,83",
        "maths": "13,33",
        "info": "13,7",
        "eps": "14,66",
        "art": "9,41",
        "moyenne": "9,54",
        "rang": "12",
        "trimestre": "3"
    },
    {
        "nom": "MABANZA Josepha",
        "dictee": "13,66",
        "exp": "12,66",
        "pc": "11,33",
        "anglais": "15,33",
        "hg": "12,66",
        "svt": "15,38",
        "maths": "15,33",
        "info": "15,72",
        "eps": "12,5",
        "art": "10,41",
        "moyenne": "13,50",
        "rang": "6",
        "trimestre": "3"
    }
];
var cinquieme1=[
    {
        "nom": "AKIERA Stéphane",
        "dictee": "24",
        "exp": "24",
        "pc": "Absent",
        "anglais": "12,75",
        "hg": "13",
        "svt": "11",
        "maths": "9",
        "info": "4,5",
        "eps": "12,66",
        "art": "12",
        "moyenne": "10,24",
        "rang": "8"
    },
    {
        "nom": "BELA TSOUEKO Destin",
        "dictee": "10,44",
        "exp": "9,1",
        "pc": "6,5",
        "anglais": "5,55",
        "hg": "3,66",
        "svt": "3,6",
        "maths": "10,25",
        "info": "12,33",
        "eps": "15",
        "art": "10,31",
        "moyenne": "7,23",
        "rang": "23"
    },
    {
        "nom": "BOUKONO Jemina",
        "dictee": "17,54",
        "exp": "18,88",
        "pc": "12,83",
        "anglais": "11,88",
        "hg": "11,91",
        "svt": "8",
        "maths": "11,33",
        "info": "12,66",
        "eps": "11,33",
        "art": "13",
        "moyenne": "10,78",
        "rang": "18"
    },
    {
        "nom": "EMVOULOU Queen",
        "dictee": "28,22",
        "exp": "23,54",
        "pc": "14,5",
        "anglais": "16,5",
        "hg": "15,16",
        "svt": "12,6",
        "maths": "15,75",
        "info": "18,33",
        "eps": "15,5",
        "art": "11",
        "moyenne": "14,26",
        "rang": "4"
    },
    {
        "nom": "FOUTI Dieu Merci",
        "dictee": "23,44",
        "exp": "22,76",
        "pc": "8,5",
        "anglais": "11,11",
        "hg": "14,16",
        "svt": "10",
        "maths": "14,7",
        "info": "15,66",
        "eps": "13,33",
        "art": "13,18",
        "moyenne": "12,24",
        "rang": "5"
    },
    {
        "nom": "HUGHES SITA Paul",
        "dictee": "14,66",
        "exp": "17,32",
        "pc": "4,5",
        "anglais": "10,56",
        "hg": "3,75",
        "svt": "7",
        "maths": "6,16",
        "info": "10,66",
        "eps": "11,33",
        "art": "9",
        "moyenne": "7,91",
        "rang": "22"
    },
    {
        "nom": "KONDJI Gédéon",
        "dictee": "22,66",
        "exp": "16",
        "pc": "12,5",
        "anglais": "10,11",
        "hg": "13,91",
        "svt": "6,17",
        "maths": "12,33",
        "info": "12",
        "eps": "15,5",
        "art": "9,25",
        "moyenne": "10,87",
        "rang": "11"
    },
    {
        "nom": "KOUMIKANA Guety",
        "dictee": "27,2",
        "exp": "22",
        "pc": "9,33",
        "anglais": "11,33",
        "hg": "7,75",
        "svt": "12,8",
        "maths": "11,66",
        "info": "11,33",
        "eps": "15",
        "art": "11,75",
        "moyenne": "11,68",
        "rang": "7"
    },
    {
        "nom": "MABIALA NGOLO",
        "dictee": "21",
        "exp": "19,66",
        "pc": "8,83",
        "anglais": "7,3",
        "hg": "11,33",
        "svt": "7",
        "maths": "13",
        "info": "13,33",
        "eps": "12",
        "art": "6,5",
        "moyenne": "10,00",
        "rang": "16"
    },
    {
        "nom": "MADY Joyce",
        "dictee": "25,1",
        "exp": "19,76",
        "pc": "8,83",
        "anglais": "9,02",
        "hg": "10",
        "svt": "5,17",
        "maths": "9,7",
        "info": "13,33",
        "eps": "15,67",
        "art": "11,37",
        "moyenne": "10,66",
        "rang": "12"
    },
    {
        "nom": "MADY Thessia",
        "dictee": "25,32",
        "exp": "20",
        "pc": "10",
        "anglais": "6,63",
        "hg": "6,33",
        "svt": "6,6",
        "maths": "8,62",
        "info": "13",
        "eps": "13,5",
        "art": "9,63",
        "moyenne": "9,97",
        "rang": "17"
    },
    {
        "nom": "MAVOUNGOU Karl",
        "dictee": "23,32",
        "exp": "15,32",
        "pc": "8,83",
        "anglais": "13,61",
        "hg": "7",
        "svt": "10",
        "maths": "11,16",
        "info": "12",
        "eps": "14,83",
        "art": "10,5",
        "moyenne": "10,55",
        "rang": "14"
    },
    {
        "nom": "MBILA Rogi",
        "dictee": "23,76",
        "exp": "19,76",
        "pc": "11,5",
        "anglais": "8,86",
        "hg": "15,66",
        "svt": "10,3",
        "maths": "11,91",
        "info": "17",
        "eps": "14,83",
        "art": "10,93",
        "moyenne": "12,04",
        "rang": "6"
    },
    {
        "nom": "MBOUMBA Carla",
        "dictee": "17,46",
        "exp": "21,44",
        "pc": "11,33",
        "anglais": "12,77",
        "hg": "7,75",
        "svt": "6,3",
        "maths": "9,25",
        "info": "15,66",
        "eps": "13,83",
        "art": "11,12",
        "moyenne": "10,58",
        "rang": "13"
    },
    {
        "nom": "MOUTREBA Dieuveille",
        "dictee": "16,1",
        "exp": "14,76",
        "pc": "7,67",
        "anglais": "6,38",
        "hg": "5,66",
        "svt": "10",
        "maths": "7",
        "info": "15",
        "eps": "12,33",
        "art": "11,06",
        "moyenne": "8,83",
        "rang": "20"
    },
    {
        "nom": "NDECKE Dorothé",
        "dictee": "16,88",
        "exp": "19,54",
        "pc": "6,5",
        "anglais": "11,83",
        "hg": "5,75",
        "svt": "10,17",
        "maths": "7,66",
        "info": "12,66",
        "eps": "15",
        "art": "11,87",
        "moyenne": "9,82",
        "rang": "19"
    },
    {
        "nom": "NGUIMBI Aimée",
        "dictee": "16,54",
        "exp": "19,22",
        "pc": "10",
        "anglais": "10,83",
        "hg": "10,75",
        "svt": "10",
        "maths": "9,33",
        "info": "11,16",
        "eps": "15,16",
        "art": "10,37",
        "moyenne": "10,28",
        "rang": "15"
    },
    {
        "nom": "NZIKI Dos Santos",
        "dictee": "30,44",
        "exp": "22,44",
        "pc": "6,67",
        "anglais": "7,27",
        "hg": "10,66",
        "svt": "6,5",
        "maths": "8,5",
        "info": "14,5",
        "eps": "15",
        "art": "10",
        "moyenne": "11,00",
        "rang": "9"
    },
    {
        "nom": "SCHIMITH Clara",
        "dictee": "35,1",
        "exp": "27,1",
        "pc": "19,33",
        "anglais": "18,44",
        "hg": "18,66",
        "svt": "16,3",
        "maths": "16,91",
        "info": "19",
        "eps": "14,5",
        "art": "17,56",
        "moyenne": "16,91",
        "rang": "1"
    },
    {
        "nom": "SEOSSOLO Jérémie",
        "dictee": "32,66",
        "exp": "23,32",
        "pc": "17,75",
        "anglais": "18,16",
        "hg": "19,91",
        "svt": "15,7",
        "maths": "14,95",
        "info": "17,5",
        "eps": "16,33",
        "art": "16,12",
        "moyenne": "16,03",
        "rang": "2"
    },
    {
        "nom": "TCHITEMBO Divine",
        "dictee": "34",
        "exp": "27,32",
        "pc": "16,5",
        "anglais": "17,5",
        "hg": "16,75",
        "svt": "14",
        "maths": "15,66",
        "info": "17,6",
        "eps": "13,5",
        "art": "14,5",
        "moyenne": "15,61",
        "rang": "3"
    },
    {
        "nom": "YOULOU Jusné",
        "dictee": "20,54",
        "exp": "20,54",
        "pc": "7,67",
        "anglais": "11,16",
        "hg": "5,41",
        "svt": "11",
        "maths": "9,16",
        "info": "12,75",
        "eps": "13,83",
        "art": "10,56",
        "moyenne": "10,22",
        "rang": "10"
    },
    {
        "nom": "ZINGA Erica",
        "dictee": "21,22",
        "exp": "15,88",
        "pc": "6,63",
        "anglais": "7,16",
        "hg": "3,75",
        "svt": "2",
        "maths": "11,75",
        "info": "11,33",
        "eps": "12",
        "art": "6,5",
        "moyenne": "8,19",
        "rang": "21"
    }
];
var cinquieme2=[];
var cinquieme3=[];
var quatrieme2=[
    {
        "nom": "BADINGA Sonia",
        "dictee": "16,33",
        "exp": "12,66",
        "pc": "9,33",
        "anglais": "17,58",
        "hg": "14,83",
        "svt": "10",
        "maths": "13,5",
        "info": "18,5",
        "eps": "12,91",
        "art": "11,62",
        "moyenne": "13,73",
        "rang": "9",
        "trimestre": "2"
    },
    {
        "nom": "BAKALA Desvie",
        "dictee": "14,33",
        "exp": "11,66",
        "pc": "8,66",
        "anglais": "14,5",
        "hg": "10,66",
        "svt": "13",
        "maths": "13,83",
        "info": "17,83",
        "eps": "11,16",
        "art": "13,41",
        "moyenne": "12,90",
        "rang": "12",
        "trimestre": "2"
    },
    {
        "nom": "BIDZOUTA Riche",
        "dictee": "12,83",
        "exp": "11",
        "pc": "8",
        "anglais": "13,17",
        "hg": "12,75",
        "svt": "13",
        "maths": "15,66",
        "info": "16,67",
        "eps": "14",
        "art": "10,7",
        "moyenne": "12,78",
        "rang": "13",
        "trimestre": "2"
    },
    {
        "nom": "BONGUI Lindsay",
        "dictee": "10,33",
        "exp": "10,16",
        "pc": "8,66",
        "anglais": "12,67",
        "hg": "10,5",
        "svt": "7",
        "maths": "13,83",
        "info": "19,17",
        "eps": "10,66",
        "art": "7,95",
        "moyenne": "11,09",
        "rang": "20",
        "trimestre": "2"
    },
    {
        "nom": "DIPIETRO Princess",
        "dictee": "17,16",
        "exp": "12",
        "pc": "17,33",
        "anglais": "19,33",
        "hg": "18,75",
        "svt": "20",
        "maths": "18,66",
        "info": "19,33",
        "eps": "13,66",
        "art": "15,41",
        "moyenne": "17,16",
        "rang": "2",
        "trimestre": "2"
    },
    {
        "nom": "ESSASSELA Guy",
        "dictee": "10,33",
        "exp": "10",
        "pc": "5,33",
        "anglais": "15,5",
        "hg": "16,66",
        "svt": "13",
        "maths": "11",
        "info": "14,5",
        "eps": "15,83",
        "art": "9,7",
        "moyenne": "12,19",
        "rang": "17",
        "trimestre": "2"
    },
    {
        "nom": "JUVENAL-BELO",
        "dictee": "15,83",
        "exp": "12",
        "pc": "13,66",
        "anglais": "18",
        "hg": "17,25",
        "svt": "15",
        "maths": "16,5",
        "info": "15,83",
        "eps": "12,25",
        "art": "12,16",
        "moyenne": "14,85",
        "rang": "5",
        "trimestre": "2"
    },
    {
        "nom": "MABIALA Evera",
        "dictee": "17,16",
        "exp": "13",
        "pc": "12",
        "anglais": "19,42",
        "hg": "14",
        "svt": "19",
        "maths": "18,66",
        "info": "19,33",
        "eps": "11,16",
        "art": "17,33",
        "moyenne": "16,11",
        "rang": "3",
        "trimestre": "2"
    },
    {
        "nom": "MADEKE Brell",
        "dictee": "11",
        "exp": "10",
        "pc": "4,66",
        "anglais": "14,58",
        "hg": "14,83",
        "svt": "15",
        "maths": "13,83",
        "info": "17,5",
        "eps": "13,33",
        "art": "10,75",
        "moyenne": "12,55",
        "rang": "15",
        "trimestre": "2"
    },
    {
        "nom": "MASSAMBA NGOMA",
        "dictee": "11",
        "exp": "10,83",
        "pc": "13,33",
        "anglais": "13,75",
        "hg": "14,66",
        "svt": "14",
        "maths": "14,5",
        "info": "17,58",
        "eps": "12,83",
        "art": "16,29",
        "moyenne": "13,88",
        "rang": "8",
        "trimestre": "2"
    },
    {
        "nom": "MAYAMA Bontemps",
        "dictee": "10,16",
        "exp": "10",
        "pc": "11",
        "anglais": "9,25",
        "hg": "13,5",
        "svt": "15",
        "maths": "14,33",
        "info": "15,83",
        "eps": "12,58",
        "art": "14,08",
        "moyenne": "12,57",
        "rang": "14",
        "trimestre": "2"
    },
    {
        "nom": "MIBAMBOU Francia",
        "dictee": "18,5",
        "exp": "14",
        "pc": "20",
        "anglais": "19,92",
        "hg": "19,91",
        "svt": "20",
        "maths": "19,5",
        "info": "19,67",
        "eps": "14,16",
        "art": "17,25",
        "moyenne": "18,29",
        "rang": "1",
        "trimestre": "2"
    },
    {
        "nom": "MIBAMBOU Franck",
        "dictee": "14",
        "exp": "11,83",
        "pc": "12",
        "anglais": "19,33",
        "hg": "18,25",
        "svt": "19",
        "maths": "18,66",
        "info": "17",
        "eps": "15,5",
        "art": "12,54",
        "moyenne": "15,81",
        "rang": "4",
        "trimestre": "2"
    },
    {
        "nom": "MPALI Arcel",
        "dictee": "11,83",
        "exp": "11",
        "pc": "3",
        "anglais": "10",
        "hg": "10",
        "svt": "7",
        "maths": "10,33",
        "info": "14,33",
        "eps": "17,25",
        "art": "8,37",
        "moyenne": "10,31",
        "rang": "21",
        "trimestre": "2"
    },
    {
        "nom": "NDINGA Ketsia",
        "dictee": "14",
        "exp": "11,83",
        "pc": "10,66",
        "anglais": "12,5",
        "hg": "16,25",
        "svt": "16",
        "maths": "13,83",
        "info": "16,5",
        "eps": "11,25",
        "art": "11,58",
        "moyenne": "13,44",
        "rang": "11",
        "trimestre": "2"
    },
    {
        "nom": "NGOMA Jessica",
        "dictee": "13",
        "exp": "11",
        "pc": "13,33",
        "anglais": "17,75",
        "hg": "12,66",
        "svt": "16",
        "maths": "17,83",
        "info": "18,16",
        "eps": "10,16",
        "art": "10,04",
        "moyenne": "13,99",
        "rang": "7",
        "trimestre": "2"
    },
    {
        "nom": "NGOMA Gislia",
        "dictee": "13",
        "exp": "11",
        "pc": "10,33",
        "anglais": "14,83",
        "hg": "14,91",
        "svt": "20",
        "maths": "13,33",
        "info": "17,75",
        "eps": "11",
        "art": "13,83",
        "moyenne": "14,00",
        "rang": "7",
        "trimestre": "2"
    },
    {
        "nom": "NGOUONIMBA Chrisna",
        "dictee": "13,5",
        "exp": "11",
        "pc": "13",
        "anglais": "16,25",
        "hg": "13,58",
        "svt": "15",
        "maths": "16,33",
        "info": "18,66",
        "eps": "13",
        "art": "13,7",
        "moyenne": "14,40",
        "rang": "6",
        "trimestre": "2"
    },
    {
        "nom": "OKOMBI Aimé Exaucé",
        "dictee": "9,66",
        "exp": "9,83",
        "pc": "8",
        "anglais": "9,83",
        "hg": "11,91",
        "svt": "14",
        "maths": "13,5",
        "info": "16,33",
        "eps": "15",
        "art": "8,04",
        "moyenne": "11,61",
        "rang": "18",
        "trimestre": "2"
    },
    {
        "nom": "ROUXI Jean-Bernard",
        "dictee": "10,16",
        "exp": "10",
        "pc": "7,33",
        "anglais": "14,33",
        "hg": "17,75",
        "svt": "10",
        "maths": "12,83",
        "info": "13,58",
        "eps": "15,83",
        "art": "11,12",
        "moyenne": "12,29",
        "rang": "16",
        "trimestre": "2"
    },
    {
        "nom": "TATY POUEBA Lielle",
        "dictee": "11,5",
        "exp": "11",
        "pc": "8,66",
        "anglais": "16",
        "hg": "17,08",
        "svt": "16",
        "maths": "14,33",
        "info": "17,67",
        "eps": "11,5",
        "art": "11,58",
        "moyenne": "13,53",
        "rang": "10",
        "trimestre": "2"
    },
    {
        "nom": "ZINGA Chavez",
        "dictee": "10,33",
        "exp": "10",
        "pc": "6,33",
        "anglais": "11,92",
        "hg": "13,41",
        "svt": "13",
        "maths": "10,16",
        "info": "12,91",
        "eps": "12,5",
        "art": "12,54",
        "moyenne": "11,31",
        "rang": "19",
        "trimestre": "2"
    }
];
var quatrieme1=[];
var quatrieme3=[];
var troisième1=[];
var troisième2=[];
var troisième3=[];
var stc1=[
    {
        "nom": "ANGALA Mahasiah",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "BOILEAU Nozioli",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "ILOKI Dieuveil",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "INKOMBOLA Merveille",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "JUVENAL-BELO",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "KENDE Séréna",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "KOUMIKANA Francida",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "LITSOKI Reflechie",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "MADEKE Brice",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "MBOUHANDI Laura",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "MBOUHANDI Loick",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "MBOUSSY Jemina",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "MFOUTOU Weelvreach",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "MONDZO Abrahamson",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "NGUIMBI Ricardo",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "NKOUNGA Béraca",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "NSITA Précieuse",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "tsoumou Gilles",
        "fr": "",
        "pc": "",
        "anglais": "",
        "hg": "",
        "svt": "",
        "maths": "",
        "philo": "",
        "eps": "",
        "moyenne": "",
        "rang": "",
        "trimestre": ""
    },
    {
        "nom": "MAQUE Jules"
    }
];
var stc2=stc1;
var stc3=stc1;
var ps1=[
    {
        "nom": "BELA Dan",
        "fr": "33,75",
        "pc": "64,55",
        "anglais": "24",
        "hg": "26,49",
        "svt": "44,15",
        "maths": "30,56",
        "philo": "22",
        "eps": "31",
        "moyenne": "9,88",
        "rang": "13",
        "trimestre": "1"
    },
    {
        "nom": "BIKOUE Rodalvie",
        "fr": "28,23",
        "pc": "69,15",
        "anglais": "33,75",
        "hg": "36,5",
        "svt": "77,5",
        "maths": "36,11",
        "philo": "17",
        "eps": "25,5",
        "moyenne": "11,56",
        "rang": "6",
        "trimestre": "1"
    },
    {
        "nom": "BOJEAN Nissi",
        "fr": "42,36",
        "pc": "88,75",
        "anglais": "51,75",
        "hg": "35,5",
        "svt": "86,65",
        "maths": "72,22",
        "philo": "24",
        "eps": "29",
        "moyenne": "15,37",
        "rang": "2",
        "trimestre": "1"
    },
    {
        "nom": "GOMA LUTA",
        "fr": "36",
        "pc": "54,55",
        "anglais": "13,5",
        "hg": "30,99",
        "svt": "35",
        "maths": "20,56",
        "philo": "15",
        "eps": "27",
        "moyenne": "8,31",
        "rang": "15",
        "trimestre": "1"
    },
    {
        "nom": "KONDJI Hamôna",
        "fr": "43,11",
        "pc": "97,5",
        "anglais": "47,25",
        "hg": "47,5",
        "svt": "95",
        "maths": "92,5",
        "philo": "29",
        "eps": "29",
        "moyenne": "17,17",
        "rang": "1",
        "trimestre": "1"
    },
    {
        "nom": "KOULENDI Andréa",
        "fr": "34,98",
        "pc": "49,55",
        "anglais": "23,25",
        "hg": "31,75",
        "svt": "67,5",
        "maths": "32,78",
        "philo": "16,5",
        "eps": "28",
        "moyenne": "10,15",
        "rang": "11",
        "trimestre": "1"
    },
    {
        "nom": "LEMBA",
        "fr": "30",
        "pc": "45",
        "anglais": "16,5",
        "hg": "22,5",
        "svt": "32,5",
        "maths": "30",
        "philo": "20",
        "eps": "27",
        "moyenne": "7,98",
        "rang": "16",
        "trimestre": "1"
    },
    {
        "nom": "MABA Synthy",
        "fr": "36",
        "pc": "56,65",
        "anglais": "13,5",
        "hg": "36",
        "svt": "35",
        "maths": "20",
        "philo": "19",
        "eps": "23,5",
        "moyenne": "8,56",
        "rang": "14",
        "trimestre": "1"
    },
    {
        "nom": "MABIALA Murielle",
        "fr": "35,49",
        "pc": "86,65",
        "anglais": "54",
        "hg": "49,5",
        "svt": "89",
        "maths": "62,22",
        "philo": "30",
        "eps": "22",
        "moyenne": "15,32",
        "rang": "3",
        "trimestre": "1"
    },
    {
        "nom": "MAHINGA Yohann",
        "fr": "33,36",
        "pc": "40",
        "anglais": "34,5",
        "hg": "36,75",
        "svt": "53,3",
        "maths": "34,44",
        "philo": "20,5",
        "eps": "29",
        "moyenne": "10,07",
        "rang": "12",
        "trimestre": "1"
    },
    {
        "nom": "MBILA Dorcas",
        "fr": "18,75",
        "pc": "42,9",
        "anglais": "16,5",
        "hg": "37,5",
        "svt": "33,5",
        "maths": "30,56",
        "philo": "15",
        "eps": "28",
        "moyenne": "7,95",
        "rang": "17",
        "trimestre": "1"
    },
    {
        "nom": "MONDZO Ruth",
        "fr": "41,73",
        "pc": "61,65",
        "anglais": "38,25",
        "hg": "38,25",
        "svt": "74,15",
        "maths": "33,33",
        "philo": "16",
        "eps": "20",
        "moyenne": "11,55",
        "rang": "7",
        "trimestre": "1"
    },
    {
        "nom": "NDINGA Merveille",
        "fr": "33",
        "pc": "70",
        "anglais": "24",
        "hg": "47,75",
        "svt": "54,15",
        "maths": "59,44",
        "philo": "21",
        "eps": "22",
        "moyenne": "11,83",
        "rang": "5",
        "trimestre": "1"
    },
    {
        "nom": "NGOUONIMBA Glenn",
        "fr": "34,11",
        "pc": "66,25",
        "anglais": "24",
        "hg": "23,25",
        "svt": "47,5",
        "maths": "53,06",
        "philo": "24",
        "eps": "24",
        "moyenne": "10,58",
        "rang": "9",
        "trimestre": "1"
    },
    {
        "nom": "NTSIETE Emmanuelle",
        "fr": "29,1",
        "pc": "87,9",
        "anglais": "47,25",
        "hg": "31",
        "svt": "70,8",
        "maths": "71,39",
        "philo": "19",
        "eps": "28,5",
        "moyenne": "13,75",
        "rang": "4",
        "trimestre": "1"
    },
    {
        "nom": "TATY Cris",
        "fr": "37,74",
        "pc": "58,5",
        "anglais": "23,25",
        "hg": "35,5",
        "svt": "32,5",
        "maths": "78,33",
        "philo": "19",
        "eps": "27,5",
        "moyenne": "11,15",
        "rang": "8",
        "trimestre": "1"
    },
    {
        "nom": "TATAY Tchiessess",
        "fr": "29,61",
        "pc": "76,65",
        "anglais": "27",
        "hg": "24,5",
        "svt": "61,65",
        "maths": "40",
        "philo": "19",
        "eps": "20",
        "moyenne": "10,66",
        "rang": "10",
        "trimestre": "1"
    }
];
var ps2=[
    {
        "nom": "BELA Dan",
        "fr": "9,16",
        "pc": "9,33",
        "anglais": "6,41",
        "hg": "10,41",
        "svt": "10,50",
        "maths": "5,75",
        "philo": "10,25",
        "eps": "13,16",
        "moyenne": "8,76",
        "rang": "13",
        "trimestre": "2"
    },
    {
        "nom": "BIKOUE Rodalvie",
        "fr": "8,33",
        "pc": "11,33",
        "anglais": "8,16",
        "hg": "11,00",
        "svt": "11,00",
        "maths": "10,42",
        "philo": "9,50",
        "eps": "9,66",
        "moyenne": "10,10",
        "rang": "10",
        "trimestre": "2"
    },
    {
        "nom": "BOJEAN Nissi",
        "fr": "10,91",
        "pc": "16,50",
        "anglais": "14,16",
        "hg": "14,33",
        "svt": "17,50",
        "maths": "14,58",
        "philo": "15,25",
        "eps": "11,25",
        "moyenne": "14,49",
        "rang": "2",
        "trimestre": "2"
    },
    {
        "nom": "GOMA LUTA",
        "fr": "9,75",
        "pc": "6,33",
        "anglais": "8,75",
        "hg": "12,50",
        "svt": "9,50",
        "maths": "5,17",
        "philo": "9,50",
        "eps": "11,66",
        "moyenne": "8,37",
        "rang": "15",
        "trimestre": "2"
    },
    {
        "nom": "KONDJI Hamôna",
        "fr": "15,58",
        "pc": "16,83",
        "anglais": "17,25",
        "hg": "16,00",
        "svt": "18,50",
        "maths": "17,37",
        "philo": "14,25",
        "eps": "12,66",
        "moyenne": "16,27",
        "rang": "1",
        "trimestre": "2"
    },
    {
        "nom": "KOULENDI Andréa",
        "fr": "8,58",
        "pc": "12,20",
        "anglais": "11,58",
        "hg": "9,25",
        "svt": "13,00",
        "maths": "7,25",
        "philo": "10,00",
        "eps": "14,75",
        "moyenne": "10,41",
        "rang": "9",
        "trimestre": "2"
    },
    {
        "nom": "MABA Synthy",
        "fr": "6,30",
        "pc": "8,41",
        "anglais": "6,91",
        "hg": "7,50",
        "svt": "7,50",
        "maths": "6,08",
        "philo": "9,00",
        "eps": "14,16",
        "moyenne": "7,92",
        "rang": "17",
        "trimestre": "2"
    },
    {
        "nom": "MABIALA Murielle",
        "fr": "13,25",
        "pc": "14,25",
        "anglais": "13,00",
        "hg": "14,83",
        "svt": "17,50",
        "maths": "10,87",
        "philo": "14,00",
        "eps": "10,33",
        "moyenne": "13,12",
        "rang": "3",
        "trimestre": "2"
    },
    {
        "nom": "MAHINGA Yohann",
        "fr": "10,33",
        "pc": "10,08",
        "anglais": "9,33",
        "hg": "8,66",
        "svt": "11,50",
        "maths": "6,33",
        "philo": "10,50",
        "eps": "13,66",
        "moyenne": "9,41",
        "rang": "11",
        "trimestre": "2"
    },
    {
        "nom": "MBILA Dorcas",
        "fr": "6,50",
        "pc": "9,83",
        "anglais": "7,33",
        "hg": "7,33",
        "svt": "8,50",
        "maths": "6,75",
        "philo": "7,50",
        "eps": "13,66",
        "moyenne": "8,29",
        "rang": "16",
        "trimestre": "2"
    },
    {
        "nom": "MONDZO Ruth",
        "fr": "12,08",
        "pc": "12,00",
        "anglais": "15,83",
        "hg": "12,75",
        "svt": "14,00",
        "maths": "9,75",
        "philo": "8,00",
        "eps": "10,65",
        "moyenne": "11,74",
        "rang": "5",
        "trimestre": "2"
    },
    {
        "nom": "NDINGA Merveille",
        "fr": "9,12",
        "pc": "12,41",
        "anglais": "7,33",
        "hg": "15,00",
        "svt": "12,50",
        "maths": "10,83",
        "philo": "11,00",
        "eps": "13,50",
        "moyenne": "11,43",
        "rang": "6",
        "trimestre": "2"
    },
    {
        "nom": "NGOUONIMBA Glenn",
        "fr": "9,08",
        "pc": "12,45",
        "anglais": "10,41",
        "hg": "12,50",
        "svt": "13,10",
        "maths": "9,16",
        "philo": "11,00",
        "eps": "10,83",
        "moyenne": "10,94",
        "rang": "8",
        "trimestre": "2"
    },
    {
        "nom": "TATY Cris",
        "fr": "9,12",
        "pc": "11,16",
        "anglais": "9,75",
        "hg": "7,58",
        "svt": "12,50",
        "maths": "12,58",
        "philo": "13,00",
        "eps": "13,66",
        "moyenne": "11,08",
        "rang": "7",
        "trimestre": "2"
    },
    {
        "nom": "TATAY Tchiessess",
        "fr": "6,16",
        "pc": "11,58",
        "anglais": "7,25",
        "hg": "11,75",
        "svt": "9,80",
        "maths": "6,62",
        "philo": "10,25",
        "eps": "9,33",
        "moyenne": "9,10",
        "rang": "12",
        "trimestre": "2"
    },
    {
        "nom": "MOUNGUELE Eunice",
        "fr": "8,04",
        "pc": "11,16",
        "anglais": "6,16",
        "hg": "8,16",
        "svt": "8,83",
        "maths": "6,16",
        "philo": "10,00",
        "eps": "15,00",
        "moyenne": "8,89",
        "rang": "14",
        "trimestre": "2"
    },
    {
        "nom": "MAQUE Préfina",
        "fr": "11,41",
        "pc": "11,45",
        "anglais": "13,16",
        "hg": "14,91",
        "svt": "12,00",
        "maths": "9,25",
        "philo": "14,25",
        "eps": "14,91",
        "moyenne": "12,21",
        "rang": "4",
        "trimestre": "2"
    }
];
var ps3=[
    {
        "nom": "BELA Dan",
        "fr": "11,16",
        "pc": "14,66",
        "anglais": "12",
        "hg": "9,91",
        "svt": "9",
        "maths": "8,33",
        "philo": "10,25",
        "eps": "16,66",
        "moyenne": "11,17",
        "rang": "9",
        "trimestre": "3"
    },
    {
        "nom": "BIKOUE Rodalvie",
        "fr": "11,83",
        "pc": "16,83",
        "anglais": "10,25",
        "hg": "14,33",
        "svt": "8,66",
        "maths": "10,25",
        "philo": "10,00",
        "eps": "7",
        "moyenne": "11,49",
        "rang": "8",
        "trimestre": "3"
    },
    {
        "nom": "BOJEAN Nissi",
        "fr": "15,41",
        "pc": "18,33",
        "anglais": "15,75",
        "hg": "16,00",
        "svt": "18,16",
        "maths": "16,83",
        "philo": "15,25",
        "eps": "15,66",
        "moyenne": "16,78",
        "rang": "1",
        "trimestre": "3"
    },
    {
        "nom": "GOMA LUTA",
        "fr": "11,54",
        "pc": "13,33",
        "anglais": "11,66",
        "hg": "11,41",
        "svt": "7,5",
        "maths": "7,50",
        "philo": "12,50",
        "eps": "11",
        "moyenne": "10,44",
        "rang": "13",
        "trimestre": "3"
    },
    {
        "nom": "KONDJI Hamôna",
        "fr": "16,54",
        "pc": "18,33",
        "anglais": "17",
        "hg": "16,33",
        "svt": "15,58",
        "maths": "15,75",
        "philo": "15,50",
        "eps": "11",
        "moyenne": "16,10",
        "rang": "2",
        "trimestre": "3"
    },
    {
        "nom": "KOULENDI Andréa",
        "fr": "12",
        "pc": "14,16",
        "anglais": "12,66",
        "hg": "10,67",
        "svt": "9",
        "maths": "7,25",
        "philo": "12,00",
        "eps": "13,66",
        "moyenne": "11,04",
        "rang": "10",
        "trimestre": "3"
    },
    {
        "nom": "MABA Synthy",
        "fr": "13",
        "pc": "11,83",
        "anglais": "11,83",
        "hg": "9,58",
        "svt": "7",
        "maths": "7,00",
        "philo": "11,50",
        "eps": "13,66",
        "moyenne": "10,09",
        "rang": "14",
        "trimestre": "3"
    },
    {
        "nom": "MABIALA Murielle",
        "fr": "14,29",
        "pc": "16,58",
        "anglais": "14,66",
        "hg": "15,50",
        "svt": "12,16",
        "maths": "12,33",
        "philo": "13,00",
        "eps": "8,33",
        "moyenne": "13,62",
        "rang": "4",
        "trimestre": "3"
    },
    {
        "nom": "MAHINGA Yohann",
        "fr": "12,5",
        "pc": "11,66",
        "anglais": "10,75",
        "hg": "9,50",
        "svt": "8,16",
        "maths": "8,58",
        "philo": "12,50",
        "eps": "16,33",
        "moyenne": "10,64",
        "rang": "12",
        "trimestre": "3"
    },
    {
        "nom": "MBILA Dorcas",
        "fr": "8,25",
        "pc": "13,58",
        "anglais": "7,33",
        "hg": "9,50",
        "svt": "6,58",
        "maths": "5,00",
        "philo": "8,50",
        "eps": "11",
        "moyenne": "8,57",
        "rang": "17",
        "trimestre": "3"
    },
    {
        "nom": "MONDZO Ruth",
        "fr": "15,37",
        "pc": "16,83",
        "anglais": "16,75",
        "hg": "14,83",
        "svt": "11",
        "maths": "6,50",
        "philo": "11,50",
        "eps": "7",
        "moyenne": "12,48",
        "rang": "6",
        "trimestre": "3"
    },
    {
        "nom": "NDINGA Merveille",
        "fr": "9,95",
        "pc": "17,75",
        "anglais": "9,41",
        "hg": "13,00",
        "svt": "10",
        "maths": "8,08",
        "philo": "13,50",
        "eps": "14,33",
        "moyenne": "11,85",
        "rang": "7",
        "trimestre": "3"
    },
    {
        "nom": "NGOUONIMBA Glenn",
        "fr": "10,83",
        "pc": "16,16",
        "anglais": "10,83",
        "hg": "9,67",
        "svt": "7,66",
        "maths": "6,92",
        "philo": "10,50",
        "eps": "15,66",
        "moyenne": "10,71",
        "rang": "11",
        "trimestre": "3"
    },
    {
        "nom": "TATY Cris",
        "fr": "14,2",
        "pc": "16,5",
        "anglais": "10",
        "hg": "11,33",
        "svt": "15,16",
        "maths": "10,17",
        "philo": "10,50",
        "eps": "16,33",
        "moyenne": "13,19",
        "rang": "5",
        "trimestre": "3"
    },
    {
        "nom": "TATAY Tchiessess",
        "fr": "9,58",
        "pc": "15",
        "anglais": "9",
        "hg": "10,08",
        "svt": "8,66",
        "maths": "5,58",
        "philo": "11,50",
        "eps": "7",
        "moyenne": "9,61",
        "rang": "15",
        "trimestre": "3"
    },
    {
        "nom": "MOUNGUELE Eunice",
        "fr": "10",
        "pc": "13,75",
        "anglais": "8,25",
        "hg": "10,50",
        "svt": "8",
        "maths": "4,50",
        "philo": "11,50",
        "eps": "14,33",
        "moyenne": "8,79",
        "rang": "16",
        "trimestre": "3"
    },
    {
        "nom": "MAQUE Préfina",
        "fr": "12,91",
        "pc": "16,83",
        "anglais": "15,42",
        "hg": "14,50",
        "svt": "13,33",
        "maths": "10,92",
        "philo": "14,00",
        "eps": "14,33",
        "moyenne": "13,94",
        "rang": "3",
        "trimestre": "3"
    }
];
var ts1=[
    {
        "nom": "BADINGA Austin",
        "fr": "8,00",
        "pc": "4,12",
        "anglais": "12,00",
        "hg": "9,75",
        "svt": "9,66",
        "maths": "3,67",
        "philo": "9,50",
        "eps": "4,08",
        "moyenne": "7,48",
        "rang": "11",
        "trimestre ": "1"
    },
    {
        "nom": "BAKALA Divin",
        "fr": "12,67",
        "pc": "11,37",
        "anglais": "15,00",
        "hg": "14,83",
        "svt": "13,11",
        "maths": "10,28",
        "philo": "13,00",
        "eps": "13,75",
        "moyenne": "12,67",
        "rang": "2",
        "trimestre ": "1"
    },
    {
        "nom": "BANTSIMBA Juste",
        "fr": "12,00",
        "pc": "12,12",
        "anglais": "11,50",
        "hg": "12,16",
        "svt": "16,05",
        "maths": "7,00",
        "philo": "8,50",
        "eps": "12,00",
        "moyenne": "11,30",
        "rang": "5",
        "trimestre ": "1"
    },
    {
        "nom": "BAYIKA Princia",
        "fr": "12,50",
        "pc": "9,46",
        "anglais": "10,00",
        "hg": "12,83",
        "svt": "12,50",
        "maths": "5,00",
        "philo": "11,75",
        "eps": "11,75",
        "moyenne": "10,52",
        "rang": "7",
        "trimestre ": "1"
    },
    {
        "nom": "KOKOLO Flora",
        "fr": "10,00",
        "pc": "4,58",
        "anglais": "9,58",
        "hg": "12,41",
        "svt": "7,72",
        "maths": "6,45",
        "philo": "9,00",
        "eps": "12,50",
        "moyenne": "8,40",
        "rang": "10",
        "trimestre ": "1"
    },
    {
        "nom": "MAVOUNGOU Nathan",
        "fr": "13,33",
        "pc": "8,87",
        "anglais": "16,00",
        "hg": "12,67",
        "svt": "10,16",
        "maths": "9,11",
        "philo": "11,00",
        "eps": "15,75",
        "moyenne": "11,50",
        "rang": "4",
        "trimestre ": "1"
    },
    {
        "nom": "MIBAMBOU Rachélia",
        "fr": "13,92",
        "pc": "14,12",
        "anglais": "11,00",
        "hg": "15,33",
        "svt": "15,27",
        "maths": "12,11",
        "philo": "12,25",
        "eps": "15,00",
        "moyenne": "13,56",
        "rang": "1",
        "trimestre ": "1"
    },
    {
        "nom": "MOSSA Nice",
        "fr": "11,33",
        "pc": "8,00",
        "anglais": "8,91",
        "hg": "11,41",
        "svt": "10,05",
        "maths": "9,45",
        "philo": "9,25",
        "eps": "13,75",
        "moyenne": "9,94",
        "rang": "8",
        "trimestre ": "1"
    },
    {
        "nom": "NGOUONIMBA Glad",
        "fr": "11,92",
        "pc": "8,25",
        "anglais": "10,75",
        "hg": "14,91",
        "svt": "9,11",
        "maths": "8,67",
        "philo": "12,50",
        "eps": "11,50",
        "moyenne": "10,53",
        "rang": "6",
        "trimestre ": "1"
    },
    {
        "nom": "OBA Gloire",
        "fr": "9,00",
        "pc": "6,37",
        "anglais": "12,00",
        "hg": "12,91",
        "svt": "6,94",
        "maths": "5,00",
        "philo": "8,75",
        "eps": "14,50",
        "moyenne": "8,70",
        "rang": "9",
        "trimestre ": "1"
    },
    {
        "nom": "YABELO Joss",
        "fr": "12,25",
        "pc": "12,58",
        "anglais": "14,58",
        "hg": "13,75",
        "svt": "13,50",
        "maths": "10,00",
        "philo": "10,25",
        "eps": "15,25",
        "moyenne": "12,50",
        "rang": "3",
        "trimestre ": "1"
    }
];
var ts2=[
    {
        "nom": "BADINGA Austin",
        "fr": "11,50",
        "pc": "7,32",
        "anglais": "8,00",
        "hg": "9,00",
        "svt": "6,77",
        "maths": "2,00",
        "philo": "7,00",
        "eps": "12,66",
        "moyenne": "7,51",
        "rang": "12",
        "trimestre": "2"
    },
    {
        "nom": "BAKALA Divin",
        "fr": "11,33",
        "pc": "7,37",
        "anglais": "15,66",
        "hg": "10,67",
        "svt": "5,78",
        "maths": "8,83",
        "philo": "9,00",
        "eps": "13,58",
        "moyenne": "9,69",
        "rang": "6",
        "trimestre": "2"
    },
    {
        "nom": "BANTSIMBA Juste",
        "fr": "11,00",
        "pc": "12,62",
        "anglais": "11,66",
        "hg": "11,16",
        "svt": "4,89",
        "maths": "6,17",
        "philo": "7,50",
        "eps": "15,08",
        "moyenne": "9,56",
        "rang": "7",
        "trimestre": "2"
    },
    {
        "nom": "BAYIKA Princia",
        "fr": "13,66",
        "pc": "11,42",
        "anglais": "10,33",
        "hg": "11,83",
        "svt": "10,61",
        "maths": "11,33",
        "philo": "10,75",
        "eps": "10,16",
        "moyenne": "11,27",
        "rang": "2",
        "trimestre": "2"
    },
    {
        "nom": "KOKOLO Flora",
        "fr": "13,00",
        "pc": "4,96",
        "anglais": "9,33",
        "hg": "11,83",
        "svt": "4,61",
        "maths": "7,00",
        "philo": "9,00",
        "eps": "10,33",
        "moyenne": "8,07",
        "rang": "10",
        "trimestre": "2"
    },
    {
        "nom": "MAVOUNGOU Nathan",
        "fr": "13,00",
        "pc": "9,37",
        "anglais": "13,66",
        "hg": "11,66",
        "svt": "9,27",
        "maths": "10,00",
        "philo": "7,50",
        "eps": "15,66",
        "moyenne": "10,79",
        "rang": "3",
        "trimestre": "2"
    },
    {
        "nom": "MIBAMBOU Rachélia",
        "fr": "14,66",
        "pc": "13,62",
        "anglais": "15,66",
        "hg": "14,83",
        "svt": "6,11",
        "maths": "10,33",
        "philo": "12,25",
        "eps": "14,66",
        "moyenne": "12,35",
        "rang": "1",
        "trimestre": "2"
    },
    {
        "nom": "MOSSA Nice",
        "fr": "13,16",
        "pc": "9,37",
        "anglais": "8,66",
        "hg": "9,33",
        "svt": "10,94",
        "maths": "2,00",
        "philo": "7,75",
        "eps": "13,66",
        "moyenne": "9,06",
        "rang": "9",
        "trimestre": "2"
    },
    {
        "nom": "NGOUONIMBA Glad",
        "fr": "14,83",
        "pc": "9,50",
        "anglais": "12,00",
        "hg": "11,50",
        "svt": "6,27",
        "maths": "5,33",
        "philo": "9,00",
        "eps": "12,33",
        "moyenne": "9,53",
        "rang": "8",
        "trimestre": "2"
    },
    {
        "nom": "OBA Gloire",
        "fr": "11,33",
        "pc": "9,37",
        "anglais": "8,00",
        "hg": "8,60",
        "svt": "5,16",
        "maths": "4,17",
        "philo": "5,25",
        "eps": "14,66",
        "moyenne": "7,79",
        "rang": "11",
        "trimestre": "2"
    },
    {
        "nom": "YABELO Joss",
        "fr": "11,83",
        "pc": "12,12",
        "anglais": "16,00",
        "hg": "9,83",
        "svt": "5,22",
        "maths": "10,67",
        "philo": "7,25",
        "eps": "16,00",
        "moyenne": "10,77",
        "rang": "4",
        "trimestre": "2"
    },
    {
        "nom": "TCHITEMBO Didienne",
        "fr": "13,66",
        "pc": "11,25",
        "anglais": "10,33",
        "hg": "14,16",
        "svt": "11,27",
        "maths": "2,50",
        "philo": "10,50",
        "eps": "10,33",
        "moyenne": "10,33",
        "rang": "5",
        "trimestre": "2"
    }
];
var ts3=[];



